apiVersion: apps/v1
kind: Deployment
metadata:
  name: exp05-deployment
spec:
  #replicas
  replicas: 3
  #selector
  selector:
    matchLabels:
      app: web
  #template
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: nginx
      #podAntiAfinity
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - web
            topologyKey: "kubernetes.io/hostname"