apiVersion: batch/v1
kind: Job #Podを直接作るのではなくJobを作成している
metadata:
  name: hello
spec:
  template: #Job が実際に起動する Pod の設計図がここに書かれている
    spec:
      containers:
      - name: hello
        image: busybox:1.28
        command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
      restartPolicy: OnFailure