apiVersion: v1
kind: Pod
metadata:
  name: secret-file-demo
spec:
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "cat /etc/secret/api-token && sleep 3600"]
    #containerにvolumeMountsすることによりコンテナからファイルとして読めるようになる
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secrets
      readOnly: true
    #env:のほうはコンテナ内に存在するためcontainers直下
    env:
    - name: SECRET_ENV
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: SECRET_ENV
  #secretNameで指定したSecretオブジェクトをPodにvolumeとしてマウントする
  #Pod内にコンテナとは別に存在するためspec:直下
  volumes:
  - name: secret-volume
    secret:
      secretName: app-secret #すでに存在するSecretオブジェクトであるapp-secretを参照