apiVersion: v1
kind: Pod
metadata:
  name: with-pod-affinity
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      #※ここも本来はpodAffinityTermでラップする必要があるが、weightがないので複数フィールドをセットにする必要がなく、podAffinityTermを省略可能
      - labelSelector: #Podを選ぶためのセレクター(NodeはnodeSelectorTermsで選ぶ)
        matchExpressions:
        - key: security
          operator: In
          values:
          - S1
        #topologyKeyにより場所の単位を指定する
        #topology.kubernetes.io/zone: プロバイダのAvailability Zone(AZ)、例:データセンタの障害単位
        topologyKey: topology.kubernetes.io/zone
    #次ができるだけ指定したPodと離すための指定
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      #weightとpodAffinityTermを一つの構造体として設定する必要がある。
      - weight: 100
        podAffinityTerm:
          labelSelector: #Podを指定するためのセレクター
            matchExpressions:
            - key: security
              operator: In
              values:
              - S2
          topologyKey: topology.kubernetes.io/zone
  containers:
  - name: widh-pod-affinity
    image: registry.k8s.io/pause:3.8