apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
spec:
  #ここからがaffinityの定義
  affinity:
    nodeAffinity:
      #この直下の条件を満たされなければPodはそのノードに配置されない(強制制御)
      requiredDuringSchedulingIgnoreDuringExecution:
        nodeSelectorTerms: #Nodeを選ぶためのセレクター
        - matchExpressions: #完全マッチ
          - key: topology.kubernetes.io/zone
            operator: In #このkeyに対する値がvalues直下のどれかに含まれていればOK
            vlaues:
            - antarctica-east1
            - antarctica-west1
      #この直下の条件は満たさなくても配置される(優先制御)
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1 #優先重みづけ
        preference:
          matchExpressions:
          - key: another-node-label-key
            operator: In
            values:
            - another-node-label-value
  #Pod内の要素をナイーブに書いていく
  containers:
  - name: with-node-affinity
    image: registry.k8s.io/pause:3.8