apiVersion: batch/v1
kind: Job
metadata:
  name: experiment-day01
spec:
  parallelism: 4   # 同時に走らせる Pod 数 (replicas に相当)
  completions: 4   # 全部で 4 個成功したら Job 完了
  backoffLimit: 0  # 失敗したら再試行しない (Pending/Failed の挙動を観察しやすく)
  template:
    metadata:
      labels:
        app: topogang
    spec:
      # Job では Always 不可。Never か OnFailure。
      restartPolicy: Never
      containers:
      - name: topogang
        image: nginx:latest
        # nginx は永遠に終わらないので sleep に差し替えて Job が Complete に到達できるようにする
        command: ["sleep", "60"]
        #gpuを利用するためrequests, limitsをここに定義しておく
        resources:
          requests:
            nvidia.com/gpu: "2"
          limits:
            nvidia.com/gpu: "2"
      #rack=Aのnodeにしか置きたくない
      affinity:
        nodeAffinity:
          #この直下の条件を満たされなければPodはそのノードに配置されない(強制制御)
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms: #Nodeを選ぶためのセレクター
            - matchExpressions: #完全マッチ
              - key: topology.example.io/rack
                operator: In
                values:
                - A
      #rack=Aの中の複数のnodeに均等に散らしたい
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: topogang
