apiVersion: v1
kind: Service
metadata:
  name: day02-app-svc
  namespace: day02
spec:
  selector: #どのPodをこのServiceの配下にするか?
    #Podにつくラベルに従ってselectorが指定するラベル名をつける
    app: day02-app #複数作成したDeploymentに負荷分散されるようにサービスとしてエンドポイントを仮想的に作成
  ports:
    - protocol: TCP
      port: 80 #Service側で見せるポート
      targetPort: 8090 #実際にPod側へ流すポート

#この後、`kubectl port-forward -n day02 svc/day02-app-svc 8080:80`によりローカルホスト⇔Serviceをつなげるようにする
#(このkubectl port-forwardはコマンド実行中しかこのトンネルはつながらない)
#しかし、この方式ではselectorで絞り込んだPod一つにしか転送を張り続けないため、結果として負荷分散できない?
#`kubectl run tmp --rm -it --image=curlimages/curl -n day02 -- sh`によりクラスタ内部でDNSを経由すれば行けるらしい?